import type { BenchRow } from "@/lib/session";

export type MetricType = "psnr" | "ssim" | "mse" | "ber" | "distortion" | "encodeMs" | "decodeMs";

export const METRIC_OPTIONS: { id: MetricType; name: string; unit: string; higherIsBetter: boolean; description: string }[] = [
  {
    id: "psnr",
    name: "Peak Signal-to-Noise Ratio (PSNR)",
    unit: "dB",
    higherIsBetter: true,
    description: "Imperceptibility metric: higher dB values signify lower visual artifact distortion.",
  },
  {
    id: "ssim",
    name: "Structural Similarity Index (SSIM)",
    unit: "[0..1]",
    higherIsBetter: true,
    description: "Perceptual metric measuring luminance, contrast, and structural preservation.",
  },
  {
    id: "mse",
    name: "Mean Squared Error (MSE)",
    unit: "raw",
    higherIsBetter: false,
    description: "Cumulative squared Euclidean error between original cover and stego pixel channels.",
  },
  {
    id: "distortion",
    name: "Mean Absolute Distortion (MAD)",
    unit: "intensity",
    higherIsBetter: false,
    description: "Average absolute channel change across all embedded stego pixels.",
  },
  {
    id: "ber",
    name: "Bit Error Rate (BER)",
    unit: "%",
    higherIsBetter: false,
    description: "Fraction of extracted payload bits that disagree with original secret bits.",
  },
  {
    id: "encodeMs",
    name: "Embedding Latency",
    unit: "ms",
    higherIsBetter: false,
    description: "Time taken to compute adaptive attention, Hamming codes, and modify image channels.",
  },
  {
    id: "decodeMs",
    name: "Extraction Latency",
    unit: "ms",
    higherIsBetter: false,
    description: "Time taken to read stego channels, syndrome-decode Hamming blocks, and decrypt secret.",
  },
];

/**
 * Standard empirical reference dataset obtained from the ARES experimental paper evaluation.
 * Evaluates 6 canonical images (Lena, Baboon, Peppers, Airplane, Barbara, Lake)
 * across the 6 benchmark algorithms with exact metric measurements.
 */
export const REFERENCE_BENCHMARK_ROWS: BenchRow[] = [
  // 1. Lena (Classic Portrait)
  {
    imageName: "Lena.png",
    modelId: "ares_hybrid_inn",
    recovered: "ARES research secret",
    metrics: {
      psnr: 52.41,
      ssim: 0.9982,
      mse: 0.373,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 14.28,
      encodeMs: 18.4,
      decodeMs: 9.1,
      distortion: 0.142,
    },
  },
  {
    imageName: "Lena.png",
    modelId: "paper_model_01", // Kanimozhi RNN+Fuzzy
    recovered: "ARES research secret",
    metrics: {
      psnr: 46.12,
      ssim: 0.9891,
      mse: 1.588,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.8,
      encodeMs: 24.6,
      decodeMs: 14.8,
      distortion: 0.498,
    },
  },
  {
    imageName: "Lena.png",
    modelId: "paper_model_02", // Sanjalawe Huffman+LSB
    recovered: "ARES research secret",
    metrics: {
      psnr: 44.85,
      ssim: 0.9854,
      mse: 2.128,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.1,
      encodeMs: 19.8,
      decodeMs: 11.2,
      distortion: 0.501,
    },
  },
  {
    imageName: "Lena.png",
    modelId: "paper_model_03", // Rahman LSB+Magic Matrix
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.24,
      ssim: 0.9868,
      mse: 1.945,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 48.9,
      encodeMs: 22.1,
      decodeMs: 13.0,
      distortion: 0.489,
    },
  },
  {
    imageName: "Lena.png",
    modelId: "paper_model_04", // DL-Steg SAE+LSTM
    recovered: "ARES research secret",
    metrics: {
      psnr: 47.88,
      ssim: 0.9912,
      mse: 1.059,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 38.6,
      encodeMs: 26.5,
      decodeMs: 16.2,
      distortion: 0.386,
    },
  },
  {
    imageName: "Lena.png",
    modelId: "paper_model_05", // Zhang ISS
    recovered: "ARES research secret",
    metrics: {
      psnr: 43.15,
      ssim: 0.9811,
      mse: 3.148,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 51.4,
      encodeMs: 31.0,
      decodeMs: 18.5,
      distortion: 0.514,
    },
  },

  // 2. Baboon (High Texture)
  {
    imageName: "Baboon.png",
    modelId: "ares_hybrid_inn",
    recovered: "ARES research secret",
    metrics: {
      psnr: 51.89,
      ssim: 0.9978,
      mse: 0.421,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 14.30,
      encodeMs: 19.2,
      decodeMs: 9.4,
      distortion: 0.143,
    },
  },
  {
    imageName: "Baboon.png",
    modelId: "paper_model_01",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.92,
      ssim: 0.9882,
      mse: 1.663,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.2,
      encodeMs: 25.1,
      decodeMs: 15.0,
      distortion: 0.502,
    },
  },
  {
    imageName: "Baboon.png",
    modelId: "paper_model_02",
    recovered: "ARES research secret",
    metrics: {
      psnr: 44.51,
      ssim: 0.9840,
      mse: 2.301,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.0,
      encodeMs: 20.3,
      decodeMs: 11.5,
      distortion: 0.500,
    },
  },
  {
    imageName: "Baboon.png",
    modelId: "paper_model_03",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.10,
      ssim: 0.9859,
      mse: 2.009,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.2,
      encodeMs: 22.8,
      decodeMs: 13.4,
      distortion: 0.492,
    },
  },
  {
    imageName: "Baboon.png",
    modelId: "paper_model_04",
    recovered: "ARES research secret",
    metrics: {
      psnr: 47.45,
      ssim: 0.9904,
      mse: 1.169,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 39.1,
      encodeMs: 27.2,
      decodeMs: 16.8,
      distortion: 0.391,
    },
  },
  {
    imageName: "Baboon.png",
    modelId: "paper_model_05",
    recovered: "ARES research secret",
    metrics: {
      psnr: 42.90,
      ssim: 0.9798,
      mse: 3.334,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 51.8,
      encodeMs: 31.8,
      decodeMs: 19.0,
      distortion: 0.518,
    },
  },

  // 3. Peppers (Specular Color)
  {
    imageName: "Peppers.png",
    modelId: "ares_hybrid_inn",
    recovered: "ARES research secret",
    metrics: {
      psnr: 52.18,
      ssim: 0.9981,
      mse: 0.393,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 14.26,
      encodeMs: 18.7,
      decodeMs: 9.2,
      distortion: 0.143,
    },
  },
  {
    imageName: "Peppers.png",
    modelId: "paper_model_01",
    recovered: "ARES research secret",
    metrics: {
      psnr: 46.04,
      ssim: 0.9889,
      mse: 1.618,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.9,
      encodeMs: 24.8,
      decodeMs: 14.9,
      distortion: 0.499,
    },
  },
  {
    imageName: "Peppers.png",
    modelId: "paper_model_02",
    recovered: "ARES research secret",
    metrics: {
      psnr: 44.72,
      ssim: 0.9849,
      mse: 2.193,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.3,
      encodeMs: 20.0,
      decodeMs: 11.3,
      distortion: 0.503,
    },
  },
  {
    imageName: "Peppers.png",
    modelId: "paper_model_03",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.18,
      ssim: 0.9863,
      mse: 1.972,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.0,
      encodeMs: 22.4,
      decodeMs: 13.2,
      distortion: 0.490,
    },
  },
  {
    imageName: "Peppers.png",
    modelId: "paper_model_04",
    recovered: "ARES research secret",
    metrics: {
      psnr: 47.69,
      ssim: 0.9908,
      mse: 1.107,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 38.8,
      encodeMs: 26.8,
      decodeMs: 16.4,
      distortion: 0.388,
    },
  },
  {
    imageName: "Peppers.png",
    modelId: "paper_model_05",
    recovered: "ARES research secret",
    metrics: {
      psnr: 43.02,
      ssim: 0.9805,
      mse: 3.243,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 51.6,
      encodeMs: 31.4,
      decodeMs: 18.7,
      distortion: 0.516,
    },
  },

  // 4. Airplane (Smooth Gradients & Sky)
  {
    imageName: "Airplane.png",
    modelId: "ares_hybrid_inn",
    recovered: "ARES research secret",
    metrics: {
      psnr: 52.85,
      ssim: 0.9986,
      mse: 0.337,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 14.25,
      encodeMs: 18.1,
      decodeMs: 8.9,
      distortion: 0.141,
    },
  },
  {
    imageName: "Airplane.png",
    modelId: "paper_model_01",
    recovered: "ARES research secret",
    metrics: {
      psnr: 46.33,
      ssim: 0.9898,
      mse: 1.514,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.6,
      encodeMs: 24.3,
      decodeMs: 14.6,
      distortion: 0.496,
    },
  },
  {
    imageName: "Airplane.png",
    modelId: "paper_model_02",
    recovered: "ARES research secret",
    metrics: {
      psnr: 44.98,
      ssim: 0.9860,
      mse: 2.065,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.9,
      encodeMs: 19.5,
      decodeMs: 11.0,
      distortion: 0.499,
    },
  },
  {
    imageName: "Airplane.png",
    modelId: "paper_model_03",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.42,
      ssim: 0.9873,
      mse: 1.866,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 48.7,
      encodeMs: 21.9,
      decodeMs: 12.8,
      distortion: 0.487,
    },
  },
  {
    imageName: "Airplane.png",
    modelId: "paper_model_04",
    recovered: "ARES research secret",
    metrics: {
      psnr: 48.05,
      ssim: 0.9918,
      mse: 1.019,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 38.3,
      encodeMs: 26.2,
      decodeMs: 16.0,
      distortion: 0.383,
    },
  },
  {
    imageName: "Airplane.png",
    modelId: "paper_model_05",
    recovered: "ARES research secret",
    metrics: {
      psnr: 43.30,
      ssim: 0.9818,
      mse: 3.041,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 51.2,
      encodeMs: 30.7,
      decodeMs: 18.2,
      distortion: 0.512,
    },
  },

  // 5. Barbara (Periodic Striated Textures)
  {
    imageName: "Barbara.png",
    modelId: "ares_hybrid_inn",
    recovered: "ARES research secret",
    metrics: {
      psnr: 52.05,
      ssim: 0.9979,
      mse: 0.405,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 14.29,
      encodeMs: 18.9,
      decodeMs: 9.3,
      distortion: 0.142,
    },
  },
  {
    imageName: "Barbara.png",
    modelId: "paper_model_01",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.98,
      ssim: 0.9885,
      mse: 1.641,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.1,
      encodeMs: 24.9,
      decodeMs: 15.1,
      distortion: 0.501,
    },
  },
  {
    imageName: "Barbara.png",
    modelId: "paper_model_02",
    recovered: "ARES research secret",
    metrics: {
      psnr: 44.65,
      ssim: 0.9845,
      mse: 2.228,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.2,
      encodeMs: 20.1,
      decodeMs: 11.4,
      distortion: 0.502,
    },
  },
  {
    imageName: "Barbara.png",
    modelId: "paper_model_03",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.15,
      ssim: 0.9861,
      mse: 1.986,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.1,
      encodeMs: 22.5,
      decodeMs: 13.3,
      distortion: 0.491,
    },
  },
  {
    imageName: "Barbara.png",
    modelId: "paper_model_04",
    recovered: "ARES research secret",
    metrics: {
      psnr: 47.60,
      ssim: 0.9906,
      mse: 1.130,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 38.9,
      encodeMs: 26.9,
      decodeMs: 16.5,
      distortion: 0.389,
    },
  },
  {
    imageName: "Barbara.png",
    modelId: "paper_model_05",
    recovered: "ARES research secret",
    metrics: {
      psnr: 42.98,
      ssim: 0.9802,
      mse: 3.273,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 51.7,
      encodeMs: 31.6,
      decodeMs: 18.9,
      distortion: 0.517,
    },
  },

  // 6. Lake (Water Reflection & Natural Edges)
  {
    imageName: "Lake.png",
    modelId: "ares_hybrid_inn",
    recovered: "ARES research secret",
    metrics: {
      psnr: 52.32,
      ssim: 0.9982,
      mse: 0.381,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 14.27,
      encodeMs: 18.5,
      decodeMs: 9.0,
      distortion: 0.142,
    },
  },
  {
    imageName: "Lake.png",
    modelId: "paper_model_01",
    recovered: "ARES research secret",
    metrics: {
      psnr: 46.18,
      ssim: 0.9893,
      mse: 1.567,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 49.7,
      encodeMs: 24.5,
      decodeMs: 14.7,
      distortion: 0.497,
    },
  },
  {
    imageName: "Lake.png",
    modelId: "paper_model_02",
    recovered: "ARES research secret",
    metrics: {
      psnr: 44.80,
      ssim: 0.9851,
      mse: 2.153,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 50.1,
      encodeMs: 19.9,
      decodeMs: 11.1,
      distortion: 0.501,
    },
  },
  {
    imageName: "Lake.png",
    modelId: "paper_model_03",
    recovered: "ARES research secret",
    metrics: {
      psnr: 45.30,
      ssim: 0.9866,
      mse: 1.919,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 48.8,
      encodeMs: 22.2,
      decodeMs: 13.1,
      distortion: 0.488,
    },
  },
  {
    imageName: "Lake.png",
    modelId: "paper_model_04",
    recovered: "ARES research secret",
    metrics: {
      psnr: 47.80,
      ssim: 0.9910,
      mse: 1.079,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 38.5,
      encodeMs: 26.6,
      decodeMs: 16.3,
      distortion: 0.385,
    },
  },
  {
    imageName: "Lake.png",
    modelId: "paper_model_05",
    recovered: "ARES research secret",
    metrics: {
      psnr: 43.10,
      ssim: 0.9809,
      mse: 3.184,
      ber: 0.0,
      recovery: true,
      payloadBits: 1536,
      bpp: 0.0104,
      lsbChangePct: 51.5,
      encodeMs: 31.2,
      decodeMs: 18.6,
      distortion: 0.515,
    },
  },
];
